---
title: "Tentative Topics Schedule"
subtitle: "Fall 2022 - University of Portland"
---

<br>

<center>**- See Books & Online Resources List for the reading materials -**</center>
<center><span style="color:red">**The readings are not mandatory but it is encouraged.**</span></center>
<center><span style="color:red">**Lecture slides will be available after class.**</span></center>

<br>

The "Reading" column in the table below contains a number on which it refers to a numbered item in the Books & Online Resources List. For example "[CV2]" refers to the first item in the list, which is our main text book titled "Calculus Volume 2". 

<br>

## **Topics and Reading Materials**

| **Week** | **Day** |                    **Topic**                   |     **Reading [CV2]**    |     **WeBWork**    |          **Activity**         | **Lab** |
|:--------:|:-------:|:----------------------------------------------:|:------------------------:|:------------------:|:-------------------------:|:-------:|
|   **1**  | 8/29(M) |        Orientation \& Calculus I review        |         Syllabus         | Integration Review |         Integral/Anti-Derivative Dominoes             |    -    |
|          | 8/31(W) |                  [5.1 Sequences](topics/20220831_5.1-sequences_class-notes.pdf){target="_blank"}                 |          Ch. 5.1         |     Section 5.1    | Syllabus Quiz (take-home) |    -    |
|          | 9/1(Th) |           [5.1 Sequences Cont. \& 5.2 Series](topics/20220901_5.1-sequences-and-5.2-series_class-notes.pdf){target="_blank"}          |  Ch 5.1 Cont. \& Ch. 5.2 |     Section 5.2    |             -             |    -    |
|          |  9/2(F) | [5.2 Series Cont. \& 5.3 Divergence Test](topics/20220902_5.2-series-and-5.3-divergence-test_class-notes.pdf){target="_blank"} | Ch. 5.2 Cont. |          -            |         -          |    -    |
|   **2**  |  9/5(M) |               [5.3 Divergence Test Cont.](topics/20220905_5.3-divergence-test-cont_class-notes.pdf){target="_blank"}             |       Ch. 5.3 Cont.      |         -          |             Geometric Series Discovery Worksheet              |    -    |
|          |  9/7(W) |              [3.7 Improper Integrals \& Sequences and Series Review](topics/20220907_3.7-improper-integrals-and-sequence-and-series-review_class-notes.pdf){target="_blank"}            |          Ch. 3.7         |         -        |             -             |    -    |
|          | 9/8(Th) |                   Assessment                   |             -            |          -         |            Convergence Quiz            |   Sequences & Series   |
|          |  9/9(F) |                [3.7 Improper Integrals Cont. \& 5.3 Integral Test](topics/20220909_3.7-improper-integrals-cont-and-5.3-integral-test_class-notes.pdf){target="_blank"}               |          Ch. 5.3         |         -        |             -             |    -    |
|     **3**     |  9/12(M) |                [5.3 Integral Test Cont.](topics/20220912_5.3-integral-test-cont_class-notes.pdf){target="_blank"}               |          Ch. 5.3         |         Section 5.3        |             Standard Integrals & Integral Test Worksheet             |    -    |
|          |  9/14(W) |                [5.3 Integral Test Cont. & 5.4 Comparison Test](topics/20220914_5.3-integral-test-cont-and-5.4-comparison-test_class-notes.pdf){target="_blank"}               |          Ch. 5.4         |         Section 3.7        |             -             |    -    |
|          |  9/15(Th) |                 Improper Integrals and Integral Test Review & Assessment               |          -         |         -        |             Improper Integrals & Integral Test Quiz             |    -    |
|          |  9/16(F) |                [5.4 Comparison Test Cont.](topics/20220916_5.4-comparison-test-cont_class-notes.pdf){target="_blank"}               |          Ch. 5.4         |         Section 5.4        |             -             |    -    |
|     **4**     |  9/19(M) |                [5.5 Alternating Series](topics/20220919_5.5-alternating-series_class-notes.pdf){target="_blank"}               |          Ch. 5.5         |         Section 5.5        |             -             |    -    |
|          |  9/21(W) |                [5.6 Ratio and Root Test](topics/20220921_5.6-ratio-and-root-test_class-notes.pdf){target="_blank"}              |          Ch. 5.6         |         Section 5.6        |             -             |    -    |
|          |  9/22(Th) |                 Assessment               |          -         |         -        |             Comparison, Alternating, Ratio and Root Test Quiz             |    Series Convergence Tests    |
|          |  9/23(F) |                Series Convergence Tests               |          -         |      -       |             Choosing a Convergence Test Worksheet             |    -    |
|     **5**     |  9/26(M) |               [1.5 Substitution](topics/20220926_1.5-substitution_class-notes.pdf){target="_blank"}               |          Ch. 1.5         |         Section 1.5        |             -             |    -    |
|          |  9/28(W) |                [1.5 Substitution Cont.](topics/20220928_1.5-substitution-cont_class-notes.pdf){target="_blank"}             |          -         |         -        |             -             |    -    |
|          |  9/29(Th) |                 All Series tests and Substitution Review & Assessment               |          -         |         -        |             All Series Tests and Substitution Quiz             |    -    |
|          |  9/30(F) |               [3.1 Integration by Parts](topics/20220930_3.1-integration-by-parts_class-notes.pdf){target="_blank"}               |          Ch. 3.1         |      Section 3.1       |             Integration by Parts Group Example Problems             |    -    |
|     **6**     |  10/3(M) |          [3.1 Integration by Parts Cont.](topics/20221003_3.1-integration-by-parts-cont_class-notes.pdf){target="_blank"}               |          -         |         -        |             -             |    -    |
|          |  10/5(W) |            [3.2 Trigonometric Integrals](topics/20221005_3.2-trigonometric-integrals_class-notes.pdf){target="_blank"}                 |          Ch. 3.2         |         Section 3.2        |             -             |    -    |
|          |  10/6(Th) |                 Assessment               |          -         |         -        |             Integration by Parts Quiz             |    -    |
|          |  10/7(F) |               [3.2 Trigonometric Integrals Cont.](topics/20221007_3.2-trigonometric-integrals-cont_class-notes.pdf){target="_blank"}               |          -         |      -       |             Trigonometric Integrals Worksheet             |    -    |
|     **7**     |  10/10(M) |          [3.3 Trigonometric Substitution](topics/20221010_3.3-trigonometric-substitution_class-notes.pdf){target="_blank"}               |          Ch. 3.3         |         Section 3.3        |             -             |    -    |
|          |  10/12(W) |            [3.3 Trigonometric Substitution Cont.](topics/20221012_3.3-trigonometric-substitution-cont_class-notes.pdf)                 |          -         |         -        |             -             |    -    |
|          |  10/13(Th) |                 Assessment               |          -         |         -        |             Trigonometric Integrals and Trigonometric Substitution Quiz             |    -    |
|          |  10/14(F) |               [3.4 Partial Fractions](topics/20221014_3.4-partial-fractions_class-notes.pdf)               |          -         |      -       |             Partial Fractions Worksheet             |    -    |
|    -    |  -  |          Fall Break               |          -         |         -        |             -             |    -    |
|     **8**     |  10/24(M) |          [3.4 Partial Fractions Cont.](topics/20221024_3.4-partial-fractions-cont_class-notes.pdf)               |          Ch. 3.3         |         Section 3.4        |             -             |    -    |
|          |  10/26(W) |            [3.4 Partial Fractions Cont. Cont.](topics/20221026_3.4-partial-fractions-cont-cont_class-notes.pdf)                 |          -         |         Additional Integration Practice        |             -             |    -    |
|          |  10/27(Th) |                 Assessment               |          -         |         -        |             Partial Fractions Quiz             |    All Integration Techniques    |
|          |  10/28(F) |               All Integration Techniques & Re-Assessments               |          -         |      -       |             -             |    -    |
|     **9**     |  10/31(M) |          [2.1 Area Between Curves](topics/20221031_2.1-area-between-curves_class-notes.pdf)               |          Ch. 2.1         |         Section 2.1        |             -             |    -    |
|          |  11/2(W) |            [2.1 Area Between Curves Cont. & 2.2 Volume by Slicing](topics/20221102_2.1-area-between-curves-cont-and-2.2-volume-by-slicing_class-notes.pdf)                 |          -         |         Section 2.2        |             -             |    -    |
|          |  11/3(Th) |                 Assessment               |          -         |         -        |             All Integration Techniques & Area Between Curves Quiz             |    -    |
|          |  11/4(F) |               [2.2 Volume by Slicing Cont.](topics/20221104_2.2-volume-by-slicing-cont_class-notes.pdf)               |          -         |      -       |             -             |    -    |
|     **10**     |  11/7(M) |          [2.2 Volume by Slicing Cont. & 2.3 Cylindrical Shells](topics/20221107_2.2-volume-by-slicing-cont-and-2.3-cylindrical-shells_class-notes.pdf)               |          Ch. 2.2         |         -        |             -             |    -    |
|          |  11/9(W) |            [2.3 Cylindrical Shells Cont.](topics/20221109_2.3-cylindrical-shells-cont_class-notes.pdf)                 |          -         |         Section 2.3        |             -             |    -    |
|          |  11/10(Th) |                 Assessments & Re-Assessments               |          -         |         -        |             Volume by disk and Washer methods, and other Core Learning Targets             |    -    |
|          |  11/11(F) |               -               |          -         |      -       |             -             |    -    |
|     **11**     |  11/14(M) |          [2.4 Arc Length of A curve and Surface Area](topics/20221114_2.4-arc-length-of-a-curve-and-surface-area_class-notes.pdf)              |          Ch. 2.4         |         Section 2.4        |             -             |    -    |
|          |  11/16(W) |            [6.1 Power Series](topics/20221116_6.1-power-series_class-notes.pdf)                 |          Ch. 6.1         |         Section 6.1        |             -             |    -    |
|          |  11/17(Th) |                 Assessments & Re-Assessments               |          -         |         -        |             Arc Length and Surface Area, and other Core Learning Targets             |    -    |
|          |  11/18(F) |               [6.2 Properties of Power Series](topics/20221118_6.2-properties-of-power-series_class-notes.pdf)               |          Ch. 6.2         |      Section 6.2       |             -             |    -    |
|     **12**     |  11/21(M) |         [6.3 Taylor and Maclaurin Series](topics/20221121_6.3-taylor-and-maclaurin-series_class-notes.pdf)              |          Ch. 6.3         |         Section 6.3        |             -             |    -    |
|          |  11/23(W) |            [6.4 Working with Taylor Series](topics/20221123_6.4-working-with-taylor-series_class-notes.pdf)                 |          Ch. 6.4         |         Section 6.4        |             -             |    -    |
|     **13**     |  11/28(M) |          [7.1 Parametric Equations](topics/20221128_7.1-parametric-equations_class-notes.pdf)              |          Ch. 7.1         |         Section 7.1        |             -             |    Volumes and Power Series    |
|          |  11/30(W) |            7.2 Calculus of Parametric Curves                 |          Ch. 7.2         |         Section 7.2        |             -             |    -    |
|          |  12/1(Th) |                 Assessments & Re-Assessments               |          -         |         -        |             Power Series, Taylor and Maclaurin Series, Parametric Equations, and other Core Learning Targets             |    -    |
|          |  12/2(F) |               7.2 Calculus of Parametric Curves Cont.               |          -         |      -       |             Parametric Curves Worksheet             |    -    |
|     **14**     |  12/5(M) |          7.3 Polar Coordinates              |          Ch. 7.3         |         Section 7.3        |             -             |    -    |
|          |  12/7(W) |            7.4 Area and Arc Length in Polar Coordinates                 |          Ch. 7.2         |         Section 7.4        |             -             |    -    |
|          |  12/8(Th) |                 Assessments & Re-Assessments               |          -         |         -        |             Calculus of Parametric Curves, Polar Coordinates, and other Core Learning Targets             |    -    |
|          |  12/9(F) |               Final Exam Review               |          -         |      -       |             -             |    -    |

<br>

## **Books & Online Resources Lists**

<br>

### Main Textbook

[CV2]   [Herman, E., Strang, G., Radulovich, W., Rutter, E. A., Smith, D., Messer, K. R., ... & McCune, D. (2016). Calculus Volume 2.](https://openstax.org/books/calculus-volume-2/pages/preface){target="_blank"}

<br>
