---
title: "Standard Integrals & Integral Test Worksheet"
subtitle: "MTH 202A - Fall 2022 - University of Portland"
header-includes: |
  \usepackage{fancyhdr}
  \pagestyle{fancy}
  \fancyhead[RO,R]{MTH 202A Calculus II - Standard Integrals \& Integral Test}
  \fancyfoot[CO,C]{}
  \fancyfoot[R]{\thepage}
  \usepackage{float}
output:
  bookdown::pdf_document2:
    toc: no
    number_section: no
urlcolor: blue
link-citations: yes
geometry: "left=1in,right=1in,top=0.25in,bottom=1in"
---

**Instructions:** Provide complete solutions for each problem. Show steps clearly and write your solutions with standard mathematical notations.

**Goals:**

  * To review how to integrate functions using the standard integral guide.
  * To apply the basic integration by substitution.
  * To put together the integral test and evaluating improper integrals.

\

**Part I: Integration Review**

(1) Evaluate the following integrals:

  a. $\displaystyle \int \frac{1}{x \sqrt{x}} \hspace{10px} dx$
  b. $\displaystyle \int 2\cos{(x)} + \frac{4}{\sqrt{4-x^2}} \hspace{10px} dx$
  
(2) Evaluate the following definite integrals:
  
  a. $\displaystyle \int_{-\pi}^{\pi} \sin{(x)} + \cos{(x)} \hspace{10px} dx$
  b. $\displaystyle \int_{2}^{e} \frac{2}{x - 1} + \frac{3}{x} \hspace{10px} dx$
  
(3) For the following integrals, identify the type of improper integral, evaluate it, and determine whether the integral converges or diverges:

  a. $\displaystyle \int_{-\infty}^0 \frac{1}{x^2 + 9} \hspace{10px} dx$
  b. $\displaystyle \int_{-1}^{1} \frac{1}{x^3} \hspace{10px} dx$

**Part II: Basic Integration by Substitution**

(4) Use basic substitution to evaluate the following integrals:

  a. $\displaystyle \int 2x(x^2 + 1)^4 \hspace{5px} dx$
  b. $\displaystyle \int \frac{x}{x^2 + 1} \hspace{5px} dx$

**Part III: Integral Test**

(5) Use the integral test to determine whether the following series converge or diverge:

  a. $\displaystyle \sum_{n=1}^{\infty} \frac{1}{(n+1)^2}$
  b. $\displaystyle \sum_{n=0}^{\infty} \frac{4n}{2n^2 + 3}$
