---
title: "Tentative Topics Schedule"
subtitle: "Fall 2022 - University of Portland"
header-includes: |
  \usepackage{fancyhdr}
  \pagestyle{fancy}
  \fancyhead[RO,R]{MTH 202A Calculus II - Syllabus}
  \fancyfoot[CO,C]{}
  \fancyfoot[R]{\thepage}
  \usepackage{float}
output:
  bookdown::pdf_document2:
    toc: yes
    number_section: no
urlcolor: blue
link-citations: yes
---

<br>

<center>**- See Books & Online Resources List for the reading materials -**</center>
<center><span style="color:red">**The readings are not mandatory but it is encouraged.**</span></center>
<center><span style="color:red">**Lecture slides will be available after class.**</span></center>

<br>

The "Reading" column in the table below contains a number on which it refers to a numbered item in the Books & Online Resources List. For example "[CV2]" refers to the first item in the list, which is our main text book titled "Calculus Volume 2". 

<br>

## **Topics and Reading Materials**

| **Week** | **Day** |                    **Topic**                   |     **Reading [CV2]**    |     **WeBWork**    |          **Quiz**         | **Lab** |
|:--------:|:-------:|:----------------------------------------------:|:------------------------:|:------------------:|:-------------------------:|:-------:|
|   **1**  | 8/29(M) |        Orientation \& Calculus I review        |         Syllabus         | Integration Review |             -             |    -    |
|          | 8/31(W) |                  5.1 Sequences                 |          Ch. 5.1         |     Section 5.1    | Syllabus Quiz (take-home) |    -    |
|          | 9/1(Th) |           5.1 Sequences \& 5.2 Series          |  Ch 5.1 Cont. \& Ch. 5.2 |     Section 5.2    |             -             |    -    |
|          |  9/2(F) | 5.2 Series \& 5.3 Divergence and Integral Test | Ch. 5.2 Cont. \& Ch. 5.3 |     Section 5.3    |             -             |    -    |
|   **2**  |  9/5(M) |               5.3 Divergence Test              |       Ch. 5.3 Cont.      |         TBA        |             -             |    -    |
|          |  9/7(W) |             3.7 Improper Integrals             |          Ch. 3.7         |         TBA        |             -             |    -    |
|          | 9/8(Th) |                   Assessment                   |             -            |          -         |            TBA            |   TBA   |
|          |  9/9(F) |                5.3 Integral Test               |       Ch. 5.3 Cont.      |         TBA        |             -             |    -    |

<br>

## **Books & Online Resources Lists**

<br>

### Main Textbook

[CV2]   [Herman, E., Strang, G., Radulovich, W., Rutter, E. A., Smith, D., Messer, K. R., ... & McCune, D. (2016). Calculus Volume 2.](https://openstax.org/books/calculus-volume-2/pages/preface){target="_blank"}

<br>

